# Generated by Django 6.1.1 on 2026-09-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='maquinarias/'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='garantia_fija',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='tarifa_diaria',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
