# Generated by Django 6.1.1 on 2026-09-29 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_maquinaria_imagen_alter_maquinaria_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaInvalidaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_intentada', models.TextField()),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='maquinaria',
            options={},
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='actualizado_el',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detallecontrato',
            name='maquinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maquinaria'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador / Ejecutivo'), ('CLIENTE', 'Empresa Constructora')], default='CLIENTE', max_length=20),
        ),
    ]
